/************************
* Version         Date           Name             Description
*==========================================================================
* V1.0            16-03-2024      Dev-1          Add method implemented
*
*/
public with sharing class Calculator {
    public Calculator() {

    }
    public integer add(integer a, integer b){
        return a+b;
    }
    public integer sub(integer a, integerb){
        return a-b;
    }
    
}